// <auto-generated />
namespace Gestion_de_Stock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ajouterRaisonsociale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajouterRaisonsociale));
        
        string IMigrationMetadata.Id
        {
            get { return "202304181042492_ajouter Raison sociale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
