// <auto-generated />
namespace Gestion_de_Stock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmettrage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmettrage));
        
        string IMigrationMetadata.Id
        {
            get { return "202306012133021_add mettrage "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
